// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOperator(arg1) {
  return window['go']['auth']['AuthHandler']['CreateOperator'](arg1);
}

export function FindAllOperators() {
  return window['go']['auth']['AuthHandler']['FindAllOperators']();
}

export function FindAppState() {
  return window['go']['auth']['AuthHandler']['FindAppState']();
}

export function SignIn(arg1) {
  return window['go']['auth']['AuthHandler']['SignIn'](arg1);
}
