// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dtos} from '../models';

export function CreateOperator(arg1:dtos.SignupDTO):Promise<dtos.AppStateDTO>;

export function FindAllOperators():Promise<Array<dtos.SummaryOperatorDTO>>;

export function FindAppState():Promise<dtos.AppStateDTO>;

export function SignIn(arg1:dtos.SignInDTO):Promise<dtos.AppStateDTO>;
