// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog-queries.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createCategory = `-- name: CreateCategory :exec

INSERT INTO category (
  id, 
  name, 
  description, 
  organization_id, 
  created_at, 
  updated_at
) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

// ------------------------------------------------------------------------------
// Category Queries
// ------------------------------------------------------------------------------
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrganizationID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createInventoryItem = `-- name: CreateInventoryItem :exec

INSERT INTO inventory_item (
  product_id, 
  organization_id, 
  stock, 
  min_stock, 
  created_at, 
  updated_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateInventoryItemParams struct {
	ProductID      string `json:"product_id"`
	OrganizationID string `json:"organization_id"`
	Stock          int64  `json:"stock"`
	MinStock       int64  `json:"min_stock"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

// ------------------------------------------------------------------------------
// Inventory Items Queries
// ------------------------------------------------------------------------------
func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) error {
	_, err := q.db.ExecContext(ctx, createInventoryItem,
		arg.ProductID,
		arg.OrganizationID,
		arg.Stock,
		arg.MinStock,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createProduct = `-- name: CreateProduct :exec

INSERT INTO product (
  id, 
  sku, 
  name, 
  description, 
  wholesale_price, 
  sale_price, 
  cost_price, 
  category_id, 
  supplier_id, 
  organization_id, 
  created_at, 
  updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID             string         `json:"id"`
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	CategoryID     sql.NullString `json:"category_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

// ------------------------------------------------------------------------------
// Product Queries
// ------------------------------------------------------------------------------
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.WholesalePrice,
		arg.SalePrice,
		arg.CostPrice,
		arg.CategoryID,
		arg.SupplierID,
		arg.OrganizationID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCategories = `-- name: DeleteCategories :exec
DELETE FROM category
WHERE id IN (/*SLICE:category_ids*/?)
AND organization_id = ?2
`

type DeleteCategoriesParams struct {
	CategoryIds    []string `json:"category_ids"`
	OrganizationID string   `json:"organization_id"`
}

func (q *Queries) DeleteCategories(ctx context.Context, arg DeleteCategoriesParams) error {
	query := deleteCategories
	var queryParams []interface{}
	if len(arg.CategoryIds) > 0 {
		for _, v := range arg.CategoryIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:category_ids*/?", strings.Repeat(",?", len(arg.CategoryIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:category_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.OrganizationID)
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category
WHERE id = ?1
AND organization_id = ?2
`

type DeleteCategoryParams struct {
	CategoryID     string `json:"category_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.CategoryID, arg.OrganizationID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
WHERE id = ?1
AND organization_id = ?2
`

type DeleteProductParams struct {
	ProductID      string `json:"product_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.ProductID, arg.OrganizationID)
	return err
}

const existsProductByNameOrSku = `-- name: ExistsProductByNameOrSku :many
SELECT name, sku FROM product
WHERE (
  lower(name) = lower(?1)
  OR sku = ?2
)
AND organization_id = ?3
AND (
  ?4 IS NULL
  OR id != ?4
)
AND deleted_at IS NULL
`

type ExistsProductByNameOrSkuParams struct {
	Name           string      `json:"name"`
	Sku            string      `json:"sku"`
	OrganizationID string      `json:"organization_id"`
	ProductID      interface{} `json:"product_id"`
}

type ExistsProductByNameOrSkuRow struct {
	Name string `json:"name"`
	Sku  string `json:"sku"`
}

func (q *Queries) ExistsProductByNameOrSku(ctx context.Context, arg ExistsProductByNameOrSkuParams) ([]ExistsProductByNameOrSkuRow, error) {
	rows, err := q.db.QueryContext(ctx, existsProductByNameOrSku,
		arg.Name,
		arg.Sku,
		arg.OrganizationID,
		arg.ProductID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExistsProductByNameOrSkuRow
	for rows.Next() {
		var i ExistsProductByNameOrSkuRow
		if err := rows.Scan(&i.Name, &i.Sku); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllCategories = `-- name: FindAllCategories :many
SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category
WHERE organization_id = ? AND deleted_at IS NULL
`

func (q *Queries) FindAllCategories(ctx context.Context, organizationID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, findAllCategories, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllProducts = `-- name: FindAllProducts :many
SELECT product.id, product.sku, product.name, product.description, product.wholesale_price, product.sale_price, product.cost_price, product.category_id, product.supplier_id, product.organization_id, product.created_at, product.updated_at, product.deleted_at, inventory_item.stock, inventory_item.min_stock
FROM product
INNER JOIN inventory_item ON inventory_item.product_id = product.id
WHERE product.organization_id = ? AND deleted_at IS NULL
`

type FindAllProductsRow struct {
	ID             string         `json:"id"`
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	CategoryID     sql.NullString `json:"category_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
	Stock          int64          `json:"stock"`
	MinStock       int64          `json:"min_stock"`
}

func (q *Queries) FindAllProducts(ctx context.Context, organizationID string) ([]FindAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllProducts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAllProductsRow
	for rows.Next() {
		var i FindAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.WholesalePrice,
			&i.SalePrice,
			&i.CostPrice,
			&i.CategoryID,
			&i.SupplierID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Stock,
			&i.MinStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneCategory = `-- name: FindOneCategory :one
SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category
WHERE id = ?1 
AND organization_id = ?2 
AND deleted_at IS NULL
`

type FindOneCategoryParams struct {
	CategoryID     string `json:"category_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneCategory(ctx context.Context, arg FindOneCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, findOneCategory, arg.CategoryID, arg.OrganizationID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOneCategoryByName = `-- name: FindOneCategoryByName :one
SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category
WHERE name = ?1 
AND organization_id = ?2 
AND deleted_at IS NULL
`

type FindOneCategoryByNameParams struct {
	CategoryName   string `json:"category_name"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneCategoryByName(ctx context.Context, arg FindOneCategoryByNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, findOneCategoryByName, arg.CategoryName, arg.OrganizationID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOneInventoryItem = `-- name: FindOneInventoryItem :one
SELECT product_id, organization_id, stock, min_stock, created_at, updated_at FROM inventory_item
WHERE inventory_item.product_id = ?1 
AND inventory_item.organization_id = ?2
`

type FindOneInventoryItemParams struct {
	ProductID      string `json:"product_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneInventoryItem(ctx context.Context, arg FindOneInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRowContext(ctx, findOneInventoryItem, arg.ProductID, arg.OrganizationID)
	var i InventoryItem
	err := row.Scan(
		&i.ProductID,
		&i.OrganizationID,
		&i.Stock,
		&i.MinStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOneProduct = `-- name: FindOneProduct :one
SELECT id, sku, name, description, wholesale_price, sale_price, cost_price, category_id, supplier_id, organization_id, created_at, updated_at, deleted_at FROM product
WHERE product.id = ?1 
AND product.organization_id = ?2 
AND product.deleted_at IS NULL
`

type FindOneProductParams struct {
	ProductID      string `json:"product_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneProduct(ctx context.Context, arg FindOneProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, findOneProduct, arg.ProductID, arg.OrganizationID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.WholesalePrice,
		&i.SalePrice,
		&i.CostPrice,
		&i.CategoryID,
		&i.SupplierID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE category 
SET 
  name = ?, 
  description = ?, 
  updated_at = ?
WHERE id = ?4 
AND organization_id = ?5 
AND deleted_at IS NULL
`

type UpdateCategoryParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	UpdatedAt      int64          `json:"updated_at"`
	CategoryID     string         `json:"category_id"`
	OrganizationID string         `json:"organization_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.CategoryID,
		arg.OrganizationID,
	)
	return err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :exec
UPDATE inventory_item 
SET stock = ?, min_stock = ?, updated_at = ?
WHERE product_id = ? AND organization_id = ?
`

type UpdateInventoryItemParams struct {
	Stock          int64  `json:"stock"`
	MinStock       int64  `json:"min_stock"`
	UpdatedAt      int64  `json:"updated_at"`
	ProductID      string `json:"product_id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) error {
	_, err := q.db.ExecContext(ctx, updateInventoryItem,
		arg.Stock,
		arg.MinStock,
		arg.UpdatedAt,
		arg.ProductID,
		arg.OrganizationID,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product 
SET 
  sku = ?, 
  name = ?, 
  description = ?, 
  wholesale_price = ?, 
  sale_price = ?, 
  cost_price = ?, 
  category_id = ?,
  supplier_id = ?,
  updated_at = ?
WHERE id = ? AND organization_id = ? AND deleted_at IS NULL
`

type UpdateProductParams struct {
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	CategoryID     sql.NullString `json:"category_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
	OrganizationID string         `json:"organization_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.WholesalePrice,
		arg.SalePrice,
		arg.CostPrice,
		arg.CategoryID,
		arg.SupplierID,
		arg.UpdatedAt,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
