// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iam-queries.sql

package db

import (
	"context"
	"database/sql"
)

const createMember = `-- name: CreateMember :exec
INSERT INTO member (id, organization_id, operator_id, role, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMemberParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	OperatorID     string `json:"operator_id"`
	Role           string `json:"role"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.ExecContext(ctx, createMember,
		arg.ID,
		arg.OrganizationID,
		arg.OperatorID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operator (id, name, username, email, pin, operator_type, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOperatorParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Pin          string `json:"pin"`
	OperatorType string `json:"operator_type"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.ExecContext(ctx, createOperator,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Pin,
		arg.OperatorType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organization (id, name, slug, logo, metadata, legal_name, address, contact_phone, contact_email, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrganizationParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Logo         sql.NullString `json:"logo"`
	Metadata     []byte         `json:"metadata"`
	LegalName    string         `json:"legal_name"`
	Address      string         `json:"address"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Metadata,
		arg.LegalName,
		arg.Address,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTeam = `-- name: CreateTeam :exec
INSERT INTO team (id, name, organization_id, permissions, description, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTeamParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	OrganizationID string         `json:"organization_id"`
	Permissions    []byte         `json:"permissions"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) error {
	_, err := q.db.ExecContext(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.OrganizationID,
		arg.Permissions,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
UPDATE member
SET deleted_at = ?
WHERE id = ? AND organization_id = ?
`

type DeleteMemberParams struct {
	DeletedAt      sql.NullInt64 `json:"deleted_at"`
	ID             string        `json:"id"`
	OrganizationID string        `json:"organization_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteMember, arg.DeletedAt, arg.ID, arg.OrganizationID)
	return err
}

const deleteOperator = `-- name: DeleteOperator :exec
DELETE FROM operator 
WHERE id = ?
`

func (q *Queries) DeleteOperator(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOperator, id)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM team
WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const deleteTeamMembers = `-- name: DeleteTeamMembers :exec
DELETE FROM team_member
WHERE team_id = ?
`

func (q *Queries) DeleteTeamMembers(ctx context.Context, teamID string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamMembers, teamID)
	return err
}

const existsOrganization = `-- name: ExistsOrganization :one

SELECT COUNT(id) as total FROM organization
WHERE (
  lower(name) = lower(?1) OR
  lower(legal_name) = lower(?2) OR
  lower(slug) = lower(?3)
) 
AND deleted_at IS NULL
`

type ExistsOrganizationParams struct {
	Name      string `json:"name"`
	LegalName string `json:"legal_name"`
	Slug      string `json:"slug"`
}

// ------------------------------------------------------------------------------
// Organization Queries
// ------------------------------------------------------------------------------
func (q *Queries) ExistsOrganization(ctx context.Context, arg ExistsOrganizationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsOrganization, arg.Name, arg.LegalName, arg.Slug)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const existsTeam = `-- name: ExistsTeam :one
SELECT COUNT(id) as total FROM team
WHERE lower(name) = lower(?1) OR 
(organization_id = ?2
AND deleted_at IS NULL)
`

type ExistsTeamParams struct {
	Name           string `json:"name"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) ExistsTeam(ctx context.Context, arg ExistsTeamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsTeam, arg.Name, arg.OrganizationID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const findAllMembers = `-- name: FindAllMembers :many

SELECT id, organization_id, operator_id, role, created_at, updated_at, deleted_at FROM member
WHERE organization_id = ? AND deleted_at IS NULL
`

// ------------------------------------------------------------------------------
// Member Queries
// ------------------------------------------------------------------------------
func (q *Queries) FindAllMembers(ctx context.Context, organizationID string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, findAllMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperatorID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTeams = `-- name: FindAllTeams :many

SELECT id, name, organization_id, permissions, description, created_at, updated_at, deleted_at FROM team
WHERE organization_id = ? AND deleted_at IS NULL
`

// ------------------------------------------------------------------------------
// Team Queries
// ------------------------------------------------------------------------------
func (q *Queries) FindAllTeams(ctx context.Context, organizationID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, findAllTeams, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.Permissions,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTeamsMembersByTeam = `-- name: FindAllTeamsMembersByTeam :many
SELECT id, team_id, operator_id, organization_id, created_at, updated_at, deleted_at FROM team_member
WHERE team_id = ? AND deleted_at IS NULL
`

func (q *Queries) FindAllTeamsMembersByTeam(ctx context.Context, teamID string) ([]TeamMember, error) {
	rows, err := q.db.QueryContext(ctx, findAllTeamsMembersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OperatorID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAppState = `-- name: FindAppState :one

SELECT id, active_organization_id, active_operator_id, updated_at FROM app_state
WHERE id = 'local'
`

// ------------------------------------------------------------------------------
// AppState Queries
// ------------------------------------------------------------------------------
func (q *Queries) FindAppState(ctx context.Context) (AppState, error) {
	row := q.db.QueryRowContext(ctx, findAppState)
	var i AppState
	err := row.Scan(
		&i.ID,
		&i.ActiveOrganizationID,
		&i.ActiveOperatorID,
		&i.UpdatedAt,
	)
	return i, err
}

const findManyOrganizationsByRootOperator = `-- name: FindManyOrganizationsByRootOperator :many
SELECT organization.id, organization.name, organization.slug, organization.logo, organization.metadata, organization.legal_name, organization.address, organization.contact_phone, organization.contact_email, organization.created_at, organization.updated_at, organization.deleted_at FROM member
INNER JOIN organization ON member.organization_id = organization.id
WHERE operator_id = ? AND role = 'ROOT'
`

func (q *Queries) FindManyOrganizationsByRootOperator(ctx context.Context, operatorID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, findManyOrganizationsByRootOperator, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Metadata,
			&i.LegalName,
			&i.Address,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneOperatorByEmail = `-- name: FindOneOperatorByEmail :one

SELECT id, name, email, username, pin, operator_type, created_at, updated_at, deleted_at FROM operator 
WHERE email = ? AND deleted_at IS NULL
`

// -----------------------------------------------------------------------------
// Operator Queries
// -----------------------------------------------------------------------------
func (q *Queries) FindOneOperatorByEmail(ctx context.Context, email string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, findOneOperatorByEmail, email)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pin,
		&i.OperatorType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOneOperatorById = `-- name: FindOneOperatorById :one
SELECT id, name, email, username, pin, operator_type, created_at, updated_at, deleted_at FROM operator 
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) FindOneOperatorById(ctx context.Context, id string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, findOneOperatorById, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pin,
		&i.OperatorType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOneOperatorByUsername = `-- name: FindOneOperatorByUsername :one
SELECT id, name, email, username, pin, operator_type, created_at, updated_at, deleted_at FROM operator 
WHERE username = ? AND deleted_at IS NULL
`

func (q *Queries) FindOneOperatorByUsername(ctx context.Context, username string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, findOneOperatorByUsername, username)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.Pin,
		&i.OperatorType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findOneOrganization = `-- name: FindOneOrganization :one
SELECT id, name, slug, logo, metadata, legal_name, address, contact_phone, contact_email, created_at, updated_at, deleted_at FROM organization
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) FindOneOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, findOneOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.Metadata,
		&i.LegalName,
		&i.Address,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOperator = `-- name: SoftDeleteOperator :exec
UPDATE operator 
SET deleted_at = ?
WHERE id = ?
`

type SoftDeleteOperatorParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteOperator(ctx context.Context, arg SoftDeleteOperatorParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteOperator, arg.DeletedAt, arg.ID)
	return err
}

const updateAppState = `-- name: UpdateAppState :exec
UPDATE app_state 
SET active_organization_id = ?, active_operator_id = ?, updated_at = ?  
WHERE id = 'local'
`

type UpdateAppStateParams struct {
	ActiveOrganizationID sql.NullString `json:"active_organization_id"`
	ActiveOperatorID     sql.NullString `json:"active_operator_id"`
	UpdatedAt            int64          `json:"updated_at"`
}

func (q *Queries) UpdateAppState(ctx context.Context, arg UpdateAppStateParams) error {
	_, err := q.db.ExecContext(ctx, updateAppState, arg.ActiveOrganizationID, arg.ActiveOperatorID, arg.UpdatedAt)
	return err
}

const updateOperator = `-- name: UpdateOperator :exec
UPDATE operator 
SET name = ?, username = ?, email = ?, pin = ?, operator_type = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateOperatorParams struct {
	Name         string `json:"name"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Pin          string `json:"pin"`
	OperatorType string `json:"operator_type"`
	UpdatedAt    int64  `json:"updated_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateOperator(ctx context.Context, arg UpdateOperatorParams) error {
	_, err := q.db.ExecContext(ctx, updateOperator,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Pin,
		arg.OperatorType,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organization 
SET name = ?, slug = ?, logo = ?, metadata = ?, legal_name = ?, address = ?, contact_phone = ?, contact_email = ?, updated_at = ?
WHERE id = ? AND deleted_at IS NULL
`

type UpdateOrganizationParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Logo         sql.NullString `json:"logo"`
	Metadata     []byte         `json:"metadata"`
	LegalName    string         `json:"legal_name"`
	Address      string         `json:"address"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	UpdatedAt    int64          `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.Metadata,
		arg.LegalName,
		arg.Address,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
