// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type AppState struct {
	ID                   string         `json:"id"`
	ActiveOrganizationID sql.NullString `json:"active_organization_id"`
	ActiveOperatorID     sql.NullString `json:"active_operator_id"`
	UpdatedAt            int64          `json:"updated_at"`
}

type Category struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type CreditPayment struct {
	ID             string         `json:"id"`
	CustomerID     string         `json:"customer_id"`
	Amount         int64          `json:"amount"`
	PaymentMethod  sql.NullString `json:"payment_method"`
	OrganizationID string         `json:"organization_id"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type Customer struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	Address        sql.NullString `json:"address"`
	CreditLimit    int64          `json:"credit_limit"`
	CurrentBalance int64          `json:"current_balance"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type Member struct {
	ID             string        `json:"id"`
	OrganizationID string        `json:"organization_id"`
	OperatorID     string        `json:"operator_id"`
	Role           string        `json:"role"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
	DeletedAt      sql.NullInt64 `json:"deleted_at"`
}

type Operator struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Username  string        `json:"username"`
	Pin       string        `json:"pin"`
	IsRoot    int64         `json:"is_root"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
	DeletedAt sql.NullInt64 `json:"deleted_at"`
}

type Organization struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Logo         sql.NullString `json:"logo"`
	Metadata     []byte         `json:"metadata"`
	LegalName    string         `json:"legal_name"`
	Address      string         `json:"address"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
}

type Product struct {
	ID             string         `json:"id"`
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	Stock          int64          `json:"stock"`
	MinStock       int64          `json:"min_stock"`
	CategoryID     sql.NullString `json:"category_id"`
	OrganizationID string         `json:"organization_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type StockMovement struct {
	ID             string         `json:"id"`
	ProductID      string         `json:"product_id"`
	Type           string         `json:"type"`
	Quantity       int64          `json:"quantity"`
	Reason         sql.NullString `json:"reason"`
	OrganizationID string         `json:"organization_id"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type Supplier struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	ContactPhone   sql.NullString `json:"contact_phone"`
	ContactEmail   sql.NullString `json:"contact_email"`
	OrganizationID string         `json:"organization_id"`
	Metadata       sql.NullString `json:"metadata"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type Team struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	OrganizationID string          `json:"organization_id"`
	Permissions    json.RawMessage `json:"permissions"`
	Description    sql.NullString  `json:"description"`
	CreatedAt      int64           `json:"created_at"`
	UpdatedAt      int64           `json:"updated_at"`
	DeletedAt      sql.NullInt64   `json:"deleted_at"`
}

type TeamMember struct {
	ID             string        `json:"id"`
	TeamID         string        `json:"team_id"`
	OperatorID     string        `json:"operator_id"`
	OrganizationID string        `json:"organization_id"`
	CreatedAt      int64         `json:"created_at"`
	UpdatedAt      int64         `json:"updated_at"`
	DeletedAt      sql.NullInt64 `json:"deleted_at"`
}

type Ticket struct {
	ID             string         `json:"id"`
	CustomerID     sql.NullString `json:"customer_id"`
	TotalAmount    int64          `json:"total_amount"`
	PaidAmount     int64          `json:"paid_amount"`
	Status         string         `json:"status"`
	PaymentMethod  string         `json:"payment_method"`
	OrganizationID string         `json:"organization_id"`
	OperatorID     string         `json:"operator_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type TicketDetail struct {
	ID             string         `json:"id"`
	TicketID       string         `json:"ticket_id"`
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SalePrice      int64          `json:"sale_price"`
	Quantity       int64          `json:"quantity"`
	SubTotal       int64          `json:"sub_total"`
	ProductID      sql.NullString `json:"product_id"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}
