// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO category (id, name, description, organization_id, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	OrganizationID string         `json:"organization_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrganizationID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMember = `-- name: CreateMember :exec
INSERT INTO member (id, organization_id, operator_id, role, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMemberParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	OperatorID     string `json:"operator_id"`
	Role           string `json:"role"`
	CreatedAt      int64  `json:"created_at"`
	UpdatedAt      int64  `json:"updated_at"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.ExecContext(ctx, createMember,
		arg.ID,
		arg.OrganizationID,
		arg.OperatorID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operator (id, name, username, email, pin, is_root, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOperatorParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Pin       string `json:"pin"`
	IsRoot    int64  `json:"is_root"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.ExecContext(ctx, createOperator,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Pin,
		arg.IsRoot,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organization (id, name, slug, legal_name, address, logo, contact_phone, contact_email, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrganizationParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	LegalName    string         `json:"legal_name"`
	Address      string         `json:"address"`
	Logo         sql.NullString `json:"logo"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LegalName,
		arg.Address,
		arg.Logo,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO product (id, sku, name, description, wholesale_price, sale_price, cost_price, stock, min_stock, category_id, organization_id, supplier_id, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID             string         `json:"id"`
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	Stock          int64          `json:"stock"`
	MinStock       int64          `json:"min_stock"`
	CategoryID     sql.NullString `json:"category_id"`
	OrganizationID string         `json:"organization_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.WholesalePrice,
		arg.SalePrice,
		arg.CostPrice,
		arg.Stock,
		arg.MinStock,
		arg.CategoryID,
		arg.OrganizationID,
		arg.SupplierID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category 
WHERE id = ? AND organization_id = ?
`

type DeleteCategoryParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID, arg.OrganizationID)
	return err
}

const findAllCategories = `-- name: FindAllCategories :many

SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category WHERE organization_id = ?
`

// -----------------------------------------------------------------------------
// Category
// -----------------------------------------------------------------------------
func (q *Queries) FindAllCategories(ctx context.Context, organizationID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, findAllCategories, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllMembersByOrganizationId = `-- name: FindAllMembersByOrganizationId :many

SELECT id, organization_id, operator_id, role, created_at, updated_at, deleted_at FROM member WHERE organization_id = ?
`

// -----------------------------------------------------------------------------
// Member
// -----------------------------------------------------------------------------
func (q *Queries) FindAllMembersByOrganizationId(ctx context.Context, organizationID string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, findAllMembersByOrganizationId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperatorID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllOperators = `-- name: FindAllOperators :many

SELECT id, name, email, username, pin, is_root, created_at, updated_at, deleted_at FROM operator
`

// -----------------------------------------------------------------------------
// Operators
// -----------------------------------------------------------------------------
func (q *Queries) FindAllOperators(ctx context.Context) ([]Operator, error) {
	rows, err := q.db.QueryContext(ctx, findAllOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Pin,
			&i.IsRoot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllProductsByOrganizationId = `-- name: FindAllProductsByOrganizationId :many
SELECT id, sku, name, description, wholesale_price, sale_price, cost_price, stock, min_stock, category_id, organization_id, supplier_id, created_at, updated_at, deleted_at FROM product WHERE organization_id = ?
`

func (q *Queries) FindAllProductsByOrganizationId(ctx context.Context, organizationID string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, findAllProductsByOrganizationId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.WholesalePrice,
			&i.SalePrice,
			&i.CostPrice,
			&i.Stock,
			&i.MinStock,
			&i.CategoryID,
			&i.OrganizationID,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTeamsByOperatorId = `-- name: FindAllTeamsByOperatorId :many
SELECT team.id, team.name, team.organization_id, team.permissions, team.description, team.created_at, team.updated_at, team.deleted_at
FROM team_member
INNER JOIN team ON team.id = team_member.team_id
WHERE team_member.operator_id = ?
GROUP BY team.id
`

func (q *Queries) FindAllTeamsByOperatorId(ctx context.Context, operatorID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, findAllTeamsByOperatorId, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.Permissions,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTeamsByOrganizationId = `-- name: FindAllTeamsByOrganizationId :many

SELECT id, name, organization_id, permissions, description, created_at, updated_at, deleted_at FROM team WHERE organization_id = ?
`

// -----------------------------------------------------------------------------
// Team
// -----------------------------------------------------------------------------
func (q *Queries) FindAllTeamsByOrganizationId(ctx context.Context, organizationID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, findAllTeamsByOrganizationId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.Permissions,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTeamsMembersByTeamId = `-- name: FindAllTeamsMembersByTeamId :many
SELECT id, team_id, operator_id, organization_id, created_at, updated_at, deleted_at FROM team_member WHERE team_id = ?
`

func (q *Queries) FindAllTeamsMembersByTeamId(ctx context.Context, teamID string) ([]TeamMember, error) {
	rows, err := q.db.QueryContext(ctx, findAllTeamsMembersByTeamId, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeamMember
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OperatorID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAppState = `-- name: FindAppState :one

SELECT id, active_organization_id, active_operator_id, updated_at FROM app_state WHERE id = "local" LIMIT 1
`

// -----------------------------------------------------------------------------
// AppState
// -----------------------------------------------------------------------------
func (q *Queries) FindAppState(ctx context.Context) (AppState, error) {
	row := q.db.QueryRowContext(ctx, findAppState)
	var i AppState
	err := row.Scan(
		&i.ID,
		&i.ActiveOrganizationID,
		&i.ActiveOperatorID,
		&i.UpdatedAt,
	)
	return i, err
}

const findManyOperatorsByEmailOrUsername = `-- name: FindManyOperatorsByEmailOrUsername :many
SELECT id, name, email, username, pin, is_root, created_at, updated_at, deleted_at FROM operator 
WHERE email = ? OR username = ?
`

type FindManyOperatorsByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) FindManyOperatorsByEmailOrUsername(ctx context.Context, arg FindManyOperatorsByEmailOrUsernameParams) ([]Operator, error) {
	rows, err := q.db.QueryContext(ctx, findManyOperatorsByEmailOrUsername, arg.Email, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Pin,
			&i.IsRoot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyOrganizationsBy = `-- name: FindManyOrganizationsBy :many
SELECT id, name, slug, logo, metadata, legal_name, address, contact_phone, contact_email, created_at, updated_at, deleted_at FROM organization
WHERE organization.slug = ? OR organization.legal_name = ? OR organization.name = ?
`

type FindManyOrganizationsByParams struct {
	Slug      string `json:"slug"`
	LegalName string `json:"legal_name"`
	Name      string `json:"name"`
}

func (q *Queries) FindManyOrganizationsBy(ctx context.Context, arg FindManyOrganizationsByParams) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, findManyOrganizationsBy, arg.Slug, arg.LegalName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Metadata,
			&i.LegalName,
			&i.Address,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findManyOrganizationsByOperatorId = `-- name: FindManyOrganizationsByOperatorId :many
SELECT organization.id, organization.name, organization.slug, organization.logo, organization.metadata, organization.legal_name, organization.address, organization.contact_phone, organization.contact_email, organization.created_at, organization.updated_at, organization.deleted_at FROM member
INNER JOIN organization ON organization.id = member.organization_id
WHERE operator_id = ?
`

func (q *Queries) FindManyOrganizationsByOperatorId(ctx context.Context, operatorID string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, findManyOrganizationsByOperatorId, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Metadata,
			&i.LegalName,
			&i.Address,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneCategoryById = `-- name: FindOneCategoryById :many
SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category WHERE id = ? AND organization_id = ? LIMIT 1
`

type FindOneCategoryByIdParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneCategoryById(ctx context.Context, arg FindOneCategoryByIdParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, findOneCategoryById, arg.ID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneCategoryByName = `-- name: FindOneCategoryByName :many
SELECT id, name, description, organization_id, created_at, updated_at, deleted_at FROM category WHERE lower(name) = lower(?) AND organization_id = ? LIMIT 1
`

type FindOneCategoryByNameParams struct {
	LOWER          string `json:"LOWER"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneCategoryByName(ctx context.Context, arg FindOneCategoryByNameParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, findOneCategoryByName, arg.LOWER, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneMemberById = `-- name: FindOneMemberById :many
SELECT id, organization_id, operator_id, role, created_at, updated_at, deleted_at FROM member m WHERE m.id = ?
`

func (q *Queries) FindOneMemberById(ctx context.Context, id string) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, findOneMemberById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OperatorID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneOperatorByEmail = `-- name: FindOneOperatorByEmail :many
SELECT id, name, email, username, pin, is_root, created_at, updated_at, deleted_at FROM operator 
WHERE email = ?
LIMIT 1
`

func (q *Queries) FindOneOperatorByEmail(ctx context.Context, email string) ([]Operator, error) {
	rows, err := q.db.QueryContext(ctx, findOneOperatorByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Pin,
			&i.IsRoot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneOperatorById = `-- name: FindOneOperatorById :many
SELECT id, name, email, username, pin, is_root, created_at, updated_at, deleted_at FROM operator 
WHERE id = ?
LIMIT 1
`

func (q *Queries) FindOneOperatorById(ctx context.Context, id string) ([]Operator, error) {
	rows, err := q.db.QueryContext(ctx, findOneOperatorById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Pin,
			&i.IsRoot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneOperatorByUsername = `-- name: FindOneOperatorByUsername :many
SELECT id, name, email, username, pin, is_root, created_at, updated_at, deleted_at FROM operator 
WHERE username = ?
LIMIT 1
`

func (q *Queries) FindOneOperatorByUsername(ctx context.Context, username string) ([]Operator, error) {
	rows, err := q.db.QueryContext(ctx, findOneOperatorByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Pin,
			&i.IsRoot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneOrganizationById = `-- name: FindOneOrganizationById :many

SELECT id, name, slug, logo, metadata, legal_name, address, contact_phone, contact_email, created_at, updated_at, deleted_at FROM organization WHERE id = ?
`

// -----------------------------------------------------------------------------
// Organization
// -----------------------------------------------------------------------------
func (q *Queries) FindOneOrganizationById(ctx context.Context, id string) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, findOneOrganizationById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.Metadata,
			&i.LegalName,
			&i.Address,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneProductById = `-- name: FindOneProductById :many
SELECT id, sku, name, description, wholesale_price, sale_price, cost_price, stock, min_stock, category_id, organization_id, supplier_id, created_at, updated_at, deleted_at FROM product WHERE id = ? AND organization_id = ? LIMIT 1
`

type FindOneProductByIdParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneProductById(ctx context.Context, arg FindOneProductByIdParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, findOneProductById, arg.ID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.WholesalePrice,
			&i.SalePrice,
			&i.CostPrice,
			&i.Stock,
			&i.MinStock,
			&i.CategoryID,
			&i.OrganizationID,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneProductByName = `-- name: FindOneProductByName :many
SELECT id, sku, name, description, wholesale_price, sale_price, cost_price, stock, min_stock, category_id, organization_id, supplier_id, created_at, updated_at, deleted_at FROM product WHERE lower(name) = lower(?) AND organization_id = ? LIMIT 1
`

type FindOneProductByNameParams struct {
	LOWER          string `json:"LOWER"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) FindOneProductByName(ctx context.Context, arg FindOneProductByNameParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, findOneProductByName, arg.LOWER, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.WholesalePrice,
			&i.SalePrice,
			&i.CostPrice,
			&i.Stock,
			&i.MinStock,
			&i.CategoryID,
			&i.OrganizationID,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOneProductBySku = `-- name: FindOneProductBySku :many

SELECT id, sku, name, description, wholesale_price, sale_price, cost_price, stock, min_stock, category_id, organization_id, supplier_id, created_at, updated_at, deleted_at FROM product WHERE sku = ? AND organization_id = ? LIMIT 1
`

type FindOneProductBySkuParams struct {
	Sku            string `json:"sku"`
	OrganizationID string `json:"organization_id"`
}

// -----------------------------------------------------------------------------
// Prodcut
// -----------------------------------------------------------------------------
func (q *Queries) FindOneProductBySku(ctx context.Context, arg FindOneProductBySkuParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, findOneProductBySku, arg.Sku, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.WholesalePrice,
			&i.SalePrice,
			&i.CostPrice,
			&i.Stock,
			&i.MinStock,
			&i.CategoryID,
			&i.OrganizationID,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE category 
SET deleted_at = ? 
WHERE id = ? AND organization_id = ?
`

type SoftDeleteCategoryParams struct {
	DeletedAt      sql.NullInt64 `json:"deleted_at"`
	ID             string        `json:"id"`
	OrganizationID string        `json:"organization_id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCategory, arg.DeletedAt, arg.ID, arg.OrganizationID)
	return err
}

const updateAppState = `-- name: UpdateAppState :exec
UPDATE app_state SET active_organization_id = ?, active_operator_id = ?, updated_at = ? WHERE id = "local"
`

type UpdateAppStateParams struct {
	ActiveOrganizationID sql.NullString `json:"active_organization_id"`
	ActiveOperatorID     sql.NullString `json:"active_operator_id"`
	UpdatedAt            int64          `json:"updated_at"`
}

func (q *Queries) UpdateAppState(ctx context.Context, arg UpdateAppStateParams) error {
	_, err := q.db.ExecContext(ctx, updateAppState, arg.ActiveOrganizationID, arg.ActiveOperatorID, arg.UpdatedAt)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE category 
SET name = ?, 
description = ?, 
updated_at = ? 
WHERE id = ? AND organization_id = ?
`

type UpdateCategoryParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
	OrganizationID string         `json:"organization_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product 
SET sku = ?, 
name = ?, 
description = ?, 
wholesale_price = ?, 
sale_price = ?, 
cost_price = ?, 
stock = ?, 
min_stock = ?, 
category_id = ?, 
supplier_id = ?, 
updated_at = ? 
WHERE id = ? AND organization_id = ?
`

type UpdateProductParams struct {
	Sku            string         `json:"sku"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	WholesalePrice int64          `json:"wholesale_price"`
	SalePrice      int64          `json:"sale_price"`
	CostPrice      int64          `json:"cost_price"`
	Stock          int64          `json:"stock"`
	MinStock       int64          `json:"min_stock"`
	CategoryID     sql.NullString `json:"category_id"`
	SupplierID     sql.NullString `json:"supplier_id"`
	UpdatedAt      int64          `json:"updated_at"`
	ID             string         `json:"id"`
	OrganizationID string         `json:"organization_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.WholesalePrice,
		arg.SalePrice,
		arg.CostPrice,
		arg.Stock,
		arg.MinStock,
		arg.CategoryID,
		arg.SupplierID,
		arg.UpdatedAt,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
