// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {responses} from '../models';

export function CreateProduct(arg1:commands.CreateProduct):Promise<responses.Product>;

export function FindAllProducts():Promise<Array<responses.Product>>;

export function UpdateProduct(arg1:commands.UpdateProduct):Promise<responses.Product>;
