// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1) {
  return window['go']['handlers']['CatalogProductHandler']['CreateProduct'](arg1);
}

export function FindAllProducts() {
  return window['go']['handlers']['CatalogProductHandler']['FindAllProducts']();
}

export function UpdateProduct(arg1) {
  return window['go']['handlers']['CatalogProductHandler']['UpdateProduct'](arg1);
}
