// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['handlers']['CatalogCategoryHandler']['CreateCategory'](arg1);
}

export function DeleteManyCategories(arg1) {
  return window['go']['handlers']['CatalogCategoryHandler']['DeleteManyCategories'](arg1);
}

export function FindAllCategories() {
  return window['go']['handlers']['CatalogCategoryHandler']['FindAllCategories']();
}

export function UpdateCategory(arg1) {
  return window['go']['handlers']['CatalogCategoryHandler']['UpdateCategory'](arg1);
}
