// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {responses} from '../models';

export function CreateTeam(arg1:commands.CreateTeam):Promise<responses.Team>;

export function DeleteTeam(arg1:commands.DeleteTeam):Promise<void>;

export function FindManyOrganizationsByRootOperator():Promise<Array<responses.Organization>>;

export function FindOneOrganization(arg1:commands.FindOneOrganization):Promise<responses.Organization>;

export function RegisterOrganization(arg1:commands.RegisterOrganization):Promise<responses.Organization>;

export function UpdateOrganization(arg1:commands.UpdateOrganization):Promise<responses.Organization>;

export function UpdateTeam(arg1:commands.UpdateTeam):Promise<void>;
