// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {responses} from '../models';
import {commands} from '../models';

export function FindManyOrganizationsByRootOperator():Promise<Array<responses.Organization>>;

export function FindOneOrganization(arg1:commands.FindOneOrganization):Promise<responses.Organization>;

export function RegisterOrganization(arg1:commands.RegisterOrganization):Promise<responses.Organization>;

export function UpdateOrganization(arg1:commands.UpdateOrganization):Promise<responses.Organization>;
