// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTeam(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['CreateTeam'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['DeleteTeam'](arg1);
}

export function FindManyOrganizationsByRootOperator() {
  return window['go']['handlers']['IamOrganizationHandler']['FindManyOrganizationsByRootOperator']();
}

export function FindOneOrganization(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['FindOneOrganization'](arg1);
}

export function RegisterOrganization(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['RegisterOrganization'](arg1);
}

export function UpdateOrganization(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['UpdateOrganization'](arg1);
}

export function UpdateTeam(arg1) {
  return window['go']['handlers']['IamOrganizationHandler']['UpdateTeam'](arg1);
}
