// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterRootOperator(arg1) {
  return window['go']['handlers']['IamSessionHandler']['RegisterRootOperator'](arg1);
}

export function SignIn(arg1) {
  return window['go']['handlers']['IamSessionHandler']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['handlers']['IamSessionHandler']['SignOut']();
}

export function SwitchOrganization(arg1) {
  return window['go']['handlers']['IamSessionHandler']['SwitchOrganization'](arg1);
}
