// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {responses} from '../models';

export function RegisterRootOperator(arg1:commands.RegisterRootOperator):Promise<responses.Operator>;

export function SignIn(arg1:commands.SignIn):Promise<responses.Operator>;

export function SignOut():Promise<void>;

export function SwitchOrganization(arg1:commands.SwitchOrganization):Promise<responses.Organization>;
