// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['catalog']['CatalogHandler']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['catalog']['CatalogHandler']['DeleteCategory'](arg1);
}

export function FindAllCategories() {
  return window['go']['catalog']['CatalogHandler']['FindAllCategories']();
}

export function UpdateCategory(arg1) {
  return window['go']['catalog']['CatalogHandler']['UpdateCategory'](arg1);
}
