// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {responses} from '../models';

export function CreateProduct(arg1:commands.CreateProductCommand):Promise<responses.ProductResponse>;

export function FindAllProducts():Promise<Array<responses.ProductResponse>>;
