/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOrgidRouteImport } from './routes/dashboard/$orgid'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DashboardOrgidIndexRouteImport } from './routes/dashboard/$orgid/index'

const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgidRoute = DashboardOrgidRouteImport.update({
  id: '/dashboard/$orgid',
  path: '/dashboard/$orgid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgidIndexRoute = DashboardOrgidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid': typeof DashboardOrgidRouteWithChildren
  '/dashboard/$orgid/': typeof DashboardOrgidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid': typeof DashboardOrgidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid': typeof DashboardOrgidRouteWithChildren
  '/dashboard/$orgid/': typeof DashboardOrgidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid'
    | '/dashboard/$orgid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid'
  id:
    | '__root__'
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid'
    | '/dashboard/$orgid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DashboardOrgidRoute: typeof DashboardOrgidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgid': {
      id: '/dashboard/$orgid'
      path: '/dashboard/$orgid'
      fullPath: '/dashboard/$orgid'
      preLoaderRoute: typeof DashboardOrgidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgid/': {
      id: '/dashboard/$orgid/'
      path: '/'
      fullPath: '/dashboard/$orgid/'
      preLoaderRoute: typeof DashboardOrgidIndexRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
  }
}

interface DashboardOrgidRouteChildren {
  DashboardOrgidIndexRoute: typeof DashboardOrgidIndexRoute
}

const DashboardOrgidRouteChildren: DashboardOrgidRouteChildren = {
  DashboardOrgidIndexRoute: DashboardOrgidIndexRoute,
}

const DashboardOrgidRouteWithChildren = DashboardOrgidRoute._addFileChildren(
  DashboardOrgidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DashboardOrgidRoute: DashboardOrgidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
