/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as RegisterOrganizationRouteImport } from './routes/register-organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOrgidRouteImport } from './routes/dashboard/$orgid'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as DashboardOrgidIndexRouteImport } from './routes/dashboard/$orgid/index'
import { Route as DashboardOrgidTeamsRouteImport } from './routes/dashboard/$orgid/teams'
import { Route as DashboardOrgidEmployeesRouteImport } from './routes/dashboard/$orgid/employees'
import { Route as DashboardOrgidClientsRouteImport } from './routes/dashboard/$orgid/clients'
import { Route as DashboardOrgidInventoryIndexRouteImport } from './routes/dashboard/$orgid/inventory/index'
import { Route as DashboardOrgidInventorySuppliersRouteImport } from './routes/dashboard/$orgid/inventory/suppliers'
import { Route as DashboardOrgidInventoryCategoriesRouteImport } from './routes/dashboard/$orgid/inventory/categories'

const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrganizationRoute = RegisterOrganizationRouteImport.update({
  id: '/register-organization',
  path: '/register-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgidRoute = DashboardOrgidRouteImport.update({
  id: '/dashboard/$orgid',
  path: '/dashboard/$orgid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgidIndexRoute = DashboardOrgidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgidRoute,
} as any)
const DashboardOrgidTeamsRoute = DashboardOrgidTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardOrgidRoute,
} as any)
const DashboardOrgidEmployeesRoute = DashboardOrgidEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardOrgidRoute,
} as any)
const DashboardOrgidClientsRoute = DashboardOrgidClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardOrgidRoute,
} as any)
const DashboardOrgidInventoryIndexRoute =
  DashboardOrgidInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => DashboardOrgidRoute,
  } as any)
const DashboardOrgidInventorySuppliersRoute =
  DashboardOrgidInventorySuppliersRouteImport.update({
    id: '/inventory/suppliers',
    path: '/inventory/suppliers',
    getParentRoute: () => DashboardOrgidRoute,
  } as any)
const DashboardOrgidInventoryCategoriesRoute =
  DashboardOrgidInventoryCategoriesRouteImport.update({
    id: '/inventory/categories',
    path: '/inventory/categories',
    getParentRoute: () => DashboardOrgidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid': typeof DashboardOrgidRouteWithChildren
  '/dashboard/$orgid/clients': typeof DashboardOrgidClientsRoute
  '/dashboard/$orgid/employees': typeof DashboardOrgidEmployeesRoute
  '/dashboard/$orgid/teams': typeof DashboardOrgidTeamsRoute
  '/dashboard/$orgid/': typeof DashboardOrgidIndexRoute
  '/dashboard/$orgid/inventory/categories': typeof DashboardOrgidInventoryCategoriesRoute
  '/dashboard/$orgid/inventory/suppliers': typeof DashboardOrgidInventorySuppliersRoute
  '/dashboard/$orgid/inventory/': typeof DashboardOrgidInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid/clients': typeof DashboardOrgidClientsRoute
  '/dashboard/$orgid/employees': typeof DashboardOrgidEmployeesRoute
  '/dashboard/$orgid/teams': typeof DashboardOrgidTeamsRoute
  '/dashboard/$orgid': typeof DashboardOrgidIndexRoute
  '/dashboard/$orgid/inventory/categories': typeof DashboardOrgidInventoryCategoriesRoute
  '/dashboard/$orgid/inventory/suppliers': typeof DashboardOrgidInventorySuppliersRoute
  '/dashboard/$orgid/inventory': typeof DashboardOrgidInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register-organization': typeof RegisterOrganizationRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/$orgid': typeof DashboardOrgidRouteWithChildren
  '/dashboard/$orgid/clients': typeof DashboardOrgidClientsRoute
  '/dashboard/$orgid/employees': typeof DashboardOrgidEmployeesRoute
  '/dashboard/$orgid/teams': typeof DashboardOrgidTeamsRoute
  '/dashboard/$orgid/': typeof DashboardOrgidIndexRoute
  '/dashboard/$orgid/inventory/categories': typeof DashboardOrgidInventoryCategoriesRoute
  '/dashboard/$orgid/inventory/suppliers': typeof DashboardOrgidInventorySuppliersRoute
  '/dashboard/$orgid/inventory/': typeof DashboardOrgidInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid'
    | '/dashboard/$orgid/clients'
    | '/dashboard/$orgid/employees'
    | '/dashboard/$orgid/teams'
    | '/dashboard/$orgid/'
    | '/dashboard/$orgid/inventory/categories'
    | '/dashboard/$orgid/inventory/suppliers'
    | '/dashboard/$orgid/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid/clients'
    | '/dashboard/$orgid/employees'
    | '/dashboard/$orgid/teams'
    | '/dashboard/$orgid'
    | '/dashboard/$orgid/inventory/categories'
    | '/dashboard/$orgid/inventory/suppliers'
    | '/dashboard/$orgid/inventory'
  id:
    | '__root__'
    | '/'
    | '/register-organization'
    | '/select-organization'
    | '/auth/sign-up'
    | '/dashboard/$orgid'
    | '/dashboard/$orgid/clients'
    | '/dashboard/$orgid/employees'
    | '/dashboard/$orgid/teams'
    | '/dashboard/$orgid/'
    | '/dashboard/$orgid/inventory/categories'
    | '/dashboard/$orgid/inventory/suppliers'
    | '/dashboard/$orgid/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterOrganizationRoute: typeof RegisterOrganizationRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DashboardOrgidRoute: typeof DashboardOrgidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-organization': {
      id: '/register-organization'
      path: '/register-organization'
      fullPath: '/register-organization'
      preLoaderRoute: typeof RegisterOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgid': {
      id: '/dashboard/$orgid'
      path: '/dashboard/$orgid'
      fullPath: '/dashboard/$orgid'
      preLoaderRoute: typeof DashboardOrgidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgid/': {
      id: '/dashboard/$orgid/'
      path: '/'
      fullPath: '/dashboard/$orgid/'
      preLoaderRoute: typeof DashboardOrgidIndexRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/teams': {
      id: '/dashboard/$orgid/teams'
      path: '/teams'
      fullPath: '/dashboard/$orgid/teams'
      preLoaderRoute: typeof DashboardOrgidTeamsRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/employees': {
      id: '/dashboard/$orgid/employees'
      path: '/employees'
      fullPath: '/dashboard/$orgid/employees'
      preLoaderRoute: typeof DashboardOrgidEmployeesRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/clients': {
      id: '/dashboard/$orgid/clients'
      path: '/clients'
      fullPath: '/dashboard/$orgid/clients'
      preLoaderRoute: typeof DashboardOrgidClientsRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/inventory/': {
      id: '/dashboard/$orgid/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/$orgid/inventory/'
      preLoaderRoute: typeof DashboardOrgidInventoryIndexRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/inventory/suppliers': {
      id: '/dashboard/$orgid/inventory/suppliers'
      path: '/inventory/suppliers'
      fullPath: '/dashboard/$orgid/inventory/suppliers'
      preLoaderRoute: typeof DashboardOrgidInventorySuppliersRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
    '/dashboard/$orgid/inventory/categories': {
      id: '/dashboard/$orgid/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/dashboard/$orgid/inventory/categories'
      preLoaderRoute: typeof DashboardOrgidInventoryCategoriesRouteImport
      parentRoute: typeof DashboardOrgidRoute
    }
  }
}

interface DashboardOrgidRouteChildren {
  DashboardOrgidClientsRoute: typeof DashboardOrgidClientsRoute
  DashboardOrgidEmployeesRoute: typeof DashboardOrgidEmployeesRoute
  DashboardOrgidTeamsRoute: typeof DashboardOrgidTeamsRoute
  DashboardOrgidIndexRoute: typeof DashboardOrgidIndexRoute
  DashboardOrgidInventoryCategoriesRoute: typeof DashboardOrgidInventoryCategoriesRoute
  DashboardOrgidInventorySuppliersRoute: typeof DashboardOrgidInventorySuppliersRoute
  DashboardOrgidInventoryIndexRoute: typeof DashboardOrgidInventoryIndexRoute
}

const DashboardOrgidRouteChildren: DashboardOrgidRouteChildren = {
  DashboardOrgidClientsRoute: DashboardOrgidClientsRoute,
  DashboardOrgidEmployeesRoute: DashboardOrgidEmployeesRoute,
  DashboardOrgidTeamsRoute: DashboardOrgidTeamsRoute,
  DashboardOrgidIndexRoute: DashboardOrgidIndexRoute,
  DashboardOrgidInventoryCategoriesRoute:
    DashboardOrgidInventoryCategoriesRoute,
  DashboardOrgidInventorySuppliersRoute: DashboardOrgidInventorySuppliersRoute,
  DashboardOrgidInventoryIndexRoute: DashboardOrgidInventoryIndexRoute,
}

const DashboardOrgidRouteWithChildren = DashboardOrgidRoute._addFileChildren(
  DashboardOrgidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterOrganizationRoute: RegisterOrganizationRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DashboardOrgidRoute: DashboardOrgidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
