// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppState() {
  return window['go']['iam']['IamHandler']['GetAppState']();
}

export function SignIn(arg1) {
  return window['go']['iam']['IamHandler']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['iam']['IamHandler']['SignOut']();
}

export function SignUp(arg1) {
  return window['go']['iam']['IamHandler']['SignUp'](arg1);
}

export function SwitchOrganization(arg1) {
  return window['go']['iam']['IamHandler']['SwitchOrganization'](arg1);
}
