// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {commands} from '../models';
import {responses} from '../models';

export function RegisterRootOperator(arg1:commands.RegisterRootOperator):Promise<responses.OperatorResponse>;
