// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindManyOrganizationsByRootOperator() {
  return window['go']['iam']['IamHandler']['FindManyOrganizationsByRootOperator']();
}

export function FindOneOrganization(arg1) {
  return window['go']['iam']['IamHandler']['FindOneOrganization'](arg1);
}

export function RegisterOrganization(arg1) {
  return window['go']['iam']['IamHandler']['RegisterOrganization'](arg1);
}

export function RegisterRootOperator(arg1) {
  return window['go']['iam']['IamHandler']['RegisterRootOperator'](arg1);
}

export function SignIn(arg1) {
  return window['go']['iam']['IamHandler']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['iam']['IamHandler']['SignOut']();
}

export function SwitchOrganization(arg1) {
  return window['go']['iam']['IamHandler']['SwitchOrganization'](arg1);
}

export function UpdateOrganization(arg1) {
  return window['go']['iam']['IamHandler']['UpdateOrganization'](arg1);
}
