// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {responses} from '../models';
import {commands} from '../models';

export function GetAppState():Promise<responses.ResponseAppState>;

export function SignIn(arg1:commands.SignInCommand):Promise<responses.ResponseAppState>;

export function SignOut():Promise<void>;

export function SignUp(arg1:commands.SignUpCommand):Promise<responses.ResponseAppState>;

export function SwitchOrganization(arg1:commands.SwitchOrganizationCommand):Promise<void>;
