// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstate} from '../models';

export function GetAppSession():Promise<appstate.SessionStateResponse>;
